#!/usr/bin/env bash

# Set application directory for cask installations
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

# Tap necessary repositories
brew tap homebrew/cask
brew tap homebrew/cask-versions
brew tap homebrew/services
brew tap buo/cask-upgrade

# Install command line tools and applications
brew install mas
brew install openssl

brew install --cask iterm2
brew install tmux

brew install --cask google-chrome

brew install git
brew install git-lfs
brew install git-extras
brew install git-secrets
brew install lazygit

brew install fish
brew install tree

brew install wget
brew install mackup

brew install node
brew install n
brew install python
brew install go
brew install lua
brew install luarocks
brew install pyenv
brew install rust

# Editing tools
brew install ripgrep
brew install fd

brew install postgresql

# Containers
brew install docker
brew install docker-compose

brew install awscli
brew install --cask aws-vault

brew install vim
brew install neovim
brew install --cask visual-studio-code

# Utilities
brew install --cask cheatsheet
brew install --cask julia
brew install --cask karabiner-elements
brew install --cask rectangle

# Install Mac App Store applications
mas install 803453959 # Slack
